
        "right_knee_x",
        "right_knee_y",
        "right_knee_z",
        "left_ankle_x",
        "left_ankle_y",
        "left_ankle_z",
        "right_ankle_x",
        "right_ankle_y",
        "right_ankle_z",
        "left_heel_x",
        "left_heel_y",
        "left_heel_z",
        "right_heel_x",